/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : eFPWM1.h
**     Project     : ProcessorExpert
**     Processor   : MC56F8257
**     Component   : Init_eFlexPWM
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.00.240
**     Compiler    : Metrowerks DSP C Compiler
**     Date/Time   : 2012-11-22, 23:31, # CodeGen: 33
**     Abstract    :
**          This file implements the eFlexPWM (eFlexPWM) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : eFPWM1
**          Device                                         : eFlexPWM
**          Settings                                       : 
**            Submodule 0                                  : Enabled
**              Submodule 0 device                         : eFlexPWM_SM0
**              Clock setting                              : 
**                PWM clock source                         : IP Bus clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 60.0000 MHz
**                Init counter value                       : 0
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 2608
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 60
**                Dead time value 1                        : 60
**                PWM frequency                            : 22.9973 kHz
**                PWM period                               : 43.4833 us
**                PWM dead time 0                          : 1.0000 us
**                PWM dead time 1                          : 1.0000 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Local reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Disabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Disabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 1                                  : Enabled
**              Submodule 1 device                         : eFlexPWM_SM1
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 60.0000 MHz
**                Init counter value                       : 0
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 2608
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 60
**                Dead time value 1                        : 60
**                PWM frequency                            : 22.9973 kHz
**                PWM period                               : 43.4833 us
**                PWM dead time 0                          : 1.0000 us
**                PWM dead time 1                          : 1.0000 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Disabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Disabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 2                                  : Enabled
**              Submodule 2 device                         : eFlexPWM_SM2
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 60.0000 MHz
**                Init counter value                       : 0
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 2608
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 60
**                Dead time value 1                        : 60
**                PWM frequency                            : 22.9973 kHz
**                PWM period                               : 43.4833 us
**                PWM dead time 0                          : 1.0000 us
**                PWM dead time 1                          : 1.0000 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Disabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Disabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 3                                  : Disabled
**            Fault channel 0 protection settings          : 
**              Common fault settings                      : 
**                Input filter                             : Disabled
**                Fault Glitch Stretch                     : Disabled
**              Fault 0                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Full cycle recovery                      : no
**              Fault 1                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Full cycle recovery                      : no
**              Fault 2                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Full cycle recovery                      : no
**              Fault 3                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Full cycle recovery                      : no
**          Pins                                           : 
**            SM0 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE1_PWM0A
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE0_PWM0B
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External synchronization                   : Disabled
**            SM1 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE3_PWM1A
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE2_PWM1B
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External synchronization                   : Disabled
**            SM2 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE5_PWM2A_XB_IN3
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE4_PWM2B_XB_IN2
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External synchronization                   : Disabled
**            SM3 pins                                     : Disabled
**            PWM Faults                                   : 
**              Fault 0                                    : Disabled
**              Fault 1                                    : Disabled
**              Fault 2                                    : Disabled
**              Fault 3                                    : Disabled
**            External clock                               : 
**              External clock                             : Disabled
**              External clock frequency                   : 1
**            External force                               : Disabled
**          Interrupts/DMA                                 : 
**            SM0 Interrupts/DMA                           : Disabled
**            SM1 Interrupts/DMA                           : Disabled
**            SM2 Interrupts/DMA                           : Disabled
**            SM3 Interrupts/DMA                           : Disabled
**            Fault interrupt                              : 
**              Interrupt                                  : INT_PWM_Fault
**              Interrupt priority                         : 2
**              ISR Name                                   : 
**              Channel 0 fault 0 interrupt                : Disabled
**              Channel 0 fault 1 interrupt                : Disabled
**              Channel 0 fault 2 interrupt                : Disabled
**              Channel 0 fault 3 interrupt                : Disabled
**            Reload error interrupt                       : 
**              Interrupt                                  : INT_PWM_ReloadError
**              Interrupt priority                         : 1
**              ISR Name                                   : 
**              SM0 reload error interrupt                 : Disabled
**              SM1 reload error interrupt                 : Disabled
**              SM2 reload error interrupt                 : Disabled
**              SM3 reload error interrupt                 : Disabled
**          Initialization                                 : 
**            Load values after init into SM0              : yes
**            Load values after init into SM1              : yes
**            Load values after init into SM2              : yes
**            Load values after init into SM3              : no
**            Enable peripheral clock for SM0              : yes
**            Enable peripheral clock for SM1              : yes
**            Enable peripheral clock for SM2              : yes
**            Enable peripheral clock for SM3              : no
**            Fault channel 0 test                         : No simulated fault
**            Fault flag clearing                          : 
**              Fault channel 0 flag 0                     : Do not initialize
**              Fault channel 0 flag 1                     : Do not initialize
**              Fault channel 0 flag 2                     : Do not initialize
**              Fault channel 0 flag 3                     : Do not initialize
**            Monitor PLL mode                             : Do not monitor PLL
**            Call Init method                             : no
**     Contents    :
**         Init - void eFPWM1_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef eFPWM1_H_
#define eFPWM1_H_

/* MODULE eFPWM1. */

/* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


void eFPWM1_Init(void);
/*
** ===================================================================
**     Method      :  eFPWM1_Init (component Init_eFlexPWM)
**
**     Description :
**         This method initializes registers of the eFlexPWM module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/


/* END eFPWM1. */
#endif /* #ifndef __eFPWM1_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 5.3 [05.01]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
