/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : eFPWM1.c
**     Project     : ProcessorExpert
**     Processor   : MC56F8257
**     Component   : Init_eFlexPWM
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.00.240
**     Compiler    : Metrowerks DSP C Compiler
**     Date/Time   : 2012-11-22, 23:31, # CodeGen: 33
**     Abstract    :
**          This file implements the eFlexPWM (eFlexPWM) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : eFPWM1
**          Device                                         : eFlexPWM
**          Settings                                       : 
**            Submodule 0                                  : Enabled
**              Submodule 0 device                         : eFlexPWM_SM0
**              Clock setting                              : 
**                PWM clock source                         : IP Bus clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 60.0000 MHz
**                Init counter value                       : 0
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 2608
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 60
**                Dead time value 1                        : 60
**                PWM frequency                            : 22.9973 kHz
**                PWM period                               : 43.4833 us
**                PWM dead time 0                          : 1.0000 us
**                PWM dead time 1                          : 1.0000 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Local reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Disabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Disabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 1                                  : Enabled
**              Submodule 1 device                         : eFlexPWM_SM1
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 60.0000 MHz
**                Init counter value                       : 0
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 2608
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 60
**                Dead time value 1                        : 60
**                PWM frequency                            : 22.9973 kHz
**                PWM period                               : 43.4833 us
**                PWM dead time 0                          : 1.0000 us
**                PWM dead time 1                          : 1.0000 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Disabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Disabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 2                                  : Enabled
**              Submodule 2 device                         : eFlexPWM_SM2
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 60.0000 MHz
**                Init counter value                       : 0
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 2608
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 60
**                Dead time value 1                        : 60
**                PWM frequency                            : 22.9973 kHz
**                PWM period                               : 43.4833 us
**                PWM dead time 0                          : 1.0000 us
**                PWM dead time 1                          : 1.0000 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : no
**                      Disable by fault 1                 : no
**                      Disable by fault 2                 : no
**                      Disable by fault 3                 : no
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Disabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Disabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 3                                  : Disabled
**            Fault channel 0 protection settings          : 
**              Common fault settings                      : 
**                Input filter                             : Disabled
**                Fault Glitch Stretch                     : Disabled
**              Fault 0                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Full cycle recovery                      : no
**              Fault 1                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Full cycle recovery                      : no
**              Fault 2                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Full cycle recovery                      : no
**              Fault 3                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Full cycle recovery                      : no
**          Pins                                           : 
**            SM0 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE1_PWM0A
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE0_PWM0B
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External synchronization                   : Disabled
**            SM1 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE3_PWM1A
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE2_PWM1B
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External synchronization                   : Disabled
**            SM2 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE5_PWM2A_XB_IN3
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE4_PWM2B_XB_IN2
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External synchronization                   : Disabled
**            SM3 pins                                     : Disabled
**            PWM Faults                                   : 
**              Fault 0                                    : Disabled
**              Fault 1                                    : Disabled
**              Fault 2                                    : Disabled
**              Fault 3                                    : Disabled
**            External clock                               : 
**              External clock                             : Disabled
**              External clock frequency                   : 1
**            External force                               : Disabled
**          Interrupts/DMA                                 : 
**            SM0 Interrupts/DMA                           : Disabled
**            SM1 Interrupts/DMA                           : Disabled
**            SM2 Interrupts/DMA                           : Disabled
**            SM3 Interrupts/DMA                           : Disabled
**            Fault interrupt                              : 
**              Interrupt                                  : INT_PWM_Fault
**              Interrupt priority                         : 2
**              ISR Name                                   : 
**              Channel 0 fault 0 interrupt                : Disabled
**              Channel 0 fault 1 interrupt                : Disabled
**              Channel 0 fault 2 interrupt                : Disabled
**              Channel 0 fault 3 interrupt                : Disabled
**            Reload error interrupt                       : 
**              Interrupt                                  : INT_PWM_ReloadError
**              Interrupt priority                         : 1
**              ISR Name                                   : 
**              SM0 reload error interrupt                 : Disabled
**              SM1 reload error interrupt                 : Disabled
**              SM2 reload error interrupt                 : Disabled
**              SM3 reload error interrupt                 : Disabled
**          Initialization                                 : 
**            Load values after init into SM0              : yes
**            Load values after init into SM1              : yes
**            Load values after init into SM2              : yes
**            Load values after init into SM3              : no
**            Enable peripheral clock for SM0              : yes
**            Enable peripheral clock for SM1              : yes
**            Enable peripheral clock for SM2              : yes
**            Enable peripheral clock for SM3              : no
**            Fault channel 0 test                         : No simulated fault
**            Fault flag clearing                          : 
**              Fault channel 0 flag 0                     : Do not initialize
**              Fault channel 0 flag 1                     : Do not initialize
**              Fault channel 0 flag 2                     : Do not initialize
**              Fault channel 0 flag 3                     : Do not initialize
**            Monitor PLL mode                             : Do not monitor PLL
**            Call Init method                             : no
**     Contents    :
**         Init - void eFPWM1_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE eFPWM1. */

#include "eFPWM1.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  eFPWM1_Init (component Init_eFlexPWM)
**
**     Description :
**         This method initializes registers of the eFlexPWM module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void eFPWM1_Init(void)
{
  /* PWM_MCTRL: IPOL&=~7,RUN&=~7,CLDOK|=7,LDOK&=~7 */
  clrSetReg16Bits(PWM_MCTRL, 0x7707U, 0x70U); 
  /* PWM_SM0_INTEN: ??=0,??=0,REIE=0,RIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWM_SM0_INTEN, 0x00U);       
  /* PWM_SM1_INTEN: ??=0,??=0,REIE=0,RIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWM_SM1_INTEN, 0x00U);       
  /* PWM_SM2_INTEN: ??=0,??=0,REIE=0,RIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWM_SM2_INTEN, 0x00U);       
  /* PWM_FCTRL: FLVL=0,FAUTO=0x0F,FSAFE=0,FIE=0 */
  setReg16(PWM_FCTRL, 0x0F00U);         
  /* PWM_SM0_OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=0,POLB=0,POLX=0,??=0,??=0,PWMAFS=0,PWMBFS=0,PWMXFS=0 */
  setReg16(PWM_SM0_OCTRL, 0x00U);       
  /* PWM_SM1_OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=0,POLB=0,POLX=0,??=0,??=0,PWMAFS=0,PWMBFS=0,PWMXFS=0 */
  setReg16(PWM_SM1_OCTRL, 0x00U);       
  /* PWM_SM2_OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=0,POLB=0,POLX=0,??=0,??=0,PWMAFS=0,PWMBFS=0,PWMXFS=0 */
  setReg16(PWM_SM2_OCTRL, 0x00U);       
  /* PWM_SM0_INIT: INIT=0 */
  setReg16(PWM_SM0_INIT, 0x00U);        
  /* PWM_SM1_INIT: INIT=0 */
  setReg16(PWM_SM1_INIT, 0x00U);        
  /* PWM_SM2_INIT: INIT=0 */
  setReg16(PWM_SM2_INIT, 0x00U);        
  /* PWM_SM0_CTRL2: DBGEN=0,WAITEN=0,INDEP=0,PWM23_INIT=0,PWM45_INIT=0,PWMX_INIT=0,INIT_SEL=0,FRCEN=0,FORCE=0,FORCE_SEL=0,RELOAD_SEL=0,CLK_SEL=0 */
  setReg16(PWM_SM0_CTRL2, 0x00U);       
  /* PWM_SM1_CTRL2: DBGEN=0,WAITEN=0,INDEP=0,PWM23_INIT=0,PWM45_INIT=0,PWMX_INIT=0,INIT_SEL=0,FRCEN=0,FORCE=0,FORCE_SEL=0,RELOAD_SEL=1,CLK_SEL=2 */
  setReg16(PWM_SM1_CTRL2, 0x06U);       
  /* PWM_SM2_CTRL2: DBGEN=0,WAITEN=0,INDEP=0,PWM23_INIT=0,PWM45_INIT=0,PWMX_INIT=0,INIT_SEL=0,FRCEN=0,FORCE=0,FORCE_SEL=0,RELOAD_SEL=1,CLK_SEL=2 */
  setReg16(PWM_SM2_CTRL2, 0x06U);       
  /* PWM_SM0_CTRL: LDFQ=0,HALF=0,FULL=0,DT=0,??=0,PRSC=0,??=0,LDMOD=0,??=0,DBLEN=0 */
  setReg16(PWM_SM0_CTRL, 0x00U);        
  /* PWM_SM1_CTRL: LDFQ=0,HALF=0,FULL=0,DT=0,??=0,PRSC=0,??=0,LDMOD=0,??=0,DBLEN=0 */
  setReg16(PWM_SM1_CTRL, 0x00U);        
  /* PWM_SM2_CTRL: LDFQ=0,HALF=0,FULL=0,DT=0,??=0,PRSC=0,??=0,LDMOD=0,??=0,DBLEN=0 */
  setReg16(PWM_SM2_CTRL, 0x00U);        
  /* PWM_SM0_TCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,OUT_TRIG_EN=0 */
  setReg16(PWM_SM0_TCTRL, 0x00U);       
  /* PWM_SM1_TCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,OUT_TRIG_EN=0 */
  setReg16(PWM_SM1_TCTRL, 0x00U);       
  /* PWM_SM2_TCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,OUT_TRIG_EN=0 */
  setReg16(PWM_SM2_TCTRL, 0x00U);       
  /* PWM_SM0_VAL0: VAL0=0 */
  setReg16(PWM_SM0_VAL0, 0x00U);        
  /* PWM_SM0_VAL1: VAL1=0x0A30 */
  setReg16(PWM_SM0_VAL1, 0x0A30U);      
  /* PWM_SM0_VAL2: VAL2=0 */
  setReg16(PWM_SM0_VAL2, 0x00U);        
  /* PWM_SM0_VAL3: VAL3=0 */
  setReg16(PWM_SM0_VAL3, 0x00U);        
  /* PWM_SM0_VAL4: VAL4=0 */
  setReg16(PWM_SM0_VAL4, 0x00U);        
  /* PWM_SM0_VAL5: VAL5=0 */
  setReg16(PWM_SM0_VAL5, 0x00U);        
  /* PWM_SM1_VAL0: VAL0=0 */
  setReg16(PWM_SM1_VAL0, 0x00U);        
  /* PWM_SM1_VAL1: VAL1=0x0A30 */
  setReg16(PWM_SM1_VAL1, 0x0A30U);      
  /* PWM_SM1_VAL2: VAL2=0 */
  setReg16(PWM_SM1_VAL2, 0x00U);        
  /* PWM_SM1_VAL3: VAL3=0 */
  setReg16(PWM_SM1_VAL3, 0x00U);        
  /* PWM_SM1_VAL4: VAL4=0 */
  setReg16(PWM_SM1_VAL4, 0x00U);        
  /* PWM_SM1_VAL5: VAL5=0 */
  setReg16(PWM_SM1_VAL5, 0x00U);        
  /* PWM_SM2_VAL0: VAL0=0 */
  setReg16(PWM_SM2_VAL0, 0x00U);        
  /* PWM_SM2_VAL1: VAL1=0x0A30 */
  setReg16(PWM_SM2_VAL1, 0x0A30U);      
  /* PWM_SM2_VAL2: VAL2=0 */
  setReg16(PWM_SM2_VAL2, 0x00U);        
  /* PWM_SM2_VAL3: VAL3=0 */
  setReg16(PWM_SM2_VAL3, 0x00U);        
  /* PWM_SM2_VAL4: VAL4=0 */
  setReg16(PWM_SM2_VAL4, 0x00U);        
  /* PWM_SM2_VAL5: VAL5=0 */
  setReg16(PWM_SM2_VAL5, 0x00U);        
  /* PWM_SM0_FRACVAL1: FRACVAL1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL1, 0x00U);    
  /* PWM_SM0_FRACVAL2: FRACVAL2=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL2, 0x00U);    
  /* PWM_SM0_FRACVAL3: FRACVAL3=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL3, 0x00U);    
  /* PWM_SM0_FRACVAL4: FRACVAL4=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL4, 0x00U);    
  /* PWM_SM0_FRACVAL5: FRACVAL5=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL5, 0x00U);    
  /* PWM_SM1_FRACVAL1: FRACVAL1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL1, 0x00U);    
  /* PWM_SM1_FRACVAL2: FRACVAL2=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL2, 0x00U);    
  /* PWM_SM1_FRACVAL3: FRACVAL3=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL3, 0x00U);    
  /* PWM_SM1_FRACVAL4: FRACVAL4=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL4, 0x00U);    
  /* PWM_SM1_FRACVAL5: FRACVAL5=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL5, 0x00U);    
  /* PWM_SM2_FRACVAL1: FRACVAL1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL1, 0x00U);    
  /* PWM_SM2_FRACVAL2: FRACVAL2=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL2, 0x00U);    
  /* PWM_SM2_FRACVAL3: FRACVAL3=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL3, 0x00U);    
  /* PWM_SM2_FRACVAL4: FRACVAL4=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL4, 0x00U);    
  /* PWM_SM2_FRACVAL5: FRACVAL5=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL5, 0x00U);    
  /* PWM_SM0_FRCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC_PU=0,??=0,??=0,??=0,FRAC45_EN=0,??=0,FRAC23_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWM_SM0_FRCTRL, 0x00U);      
  /* PWM_SM1_FRCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC_PU=0,??=0,??=0,??=0,FRAC45_EN=0,??=0,FRAC23_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWM_SM1_FRCTRL, 0x00U);      
  /* PWM_SM2_FRCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC_PU=0,??=0,??=0,??=0,FRAC45_EN=0,??=0,FRAC23_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWM_SM2_FRCTRL, 0x00U);      
  /* PWM_SM0_DISMAP: ??=1,??=1,??=1,??=1,DISX=0,DISB=0,DISA=0 */
  setReg16(PWM_SM0_DISMAP, 0xF000U);    
  /* PWM_SM1_DISMAP: ??=1,??=1,??=1,??=1,DISX=0,DISB=0,DISA=0 */
  setReg16(PWM_SM1_DISMAP, 0xF000U);    
  /* PWM_SM2_DISMAP: ??=1,??=1,??=1,??=1,DISX=0,DISB=0,DISA=0 */
  setReg16(PWM_SM2_DISMAP, 0xF000U);    
  /* PWM_SM0_DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0x3C */
  setReg16(PWM_SM0_DTCNT0, 0x3CU);      
  /* PWM_SM0_DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0x3C */
  setReg16(PWM_SM0_DTCNT1, 0x3CU);      
  /* PWM_SM1_DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0x3C */
  setReg16(PWM_SM1_DTCNT0, 0x3CU);      
  /* PWM_SM1_DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0x3C */
  setReg16(PWM_SM1_DTCNT1, 0x3CU);      
  /* PWM_SM2_DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0x3C */
  setReg16(PWM_SM2_DTCNT0, 0x3CU);      
  /* PWM_SM2_DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0x3C */
  setReg16(PWM_SM2_DTCNT1, 0x3CU);      
  /* PWM_FFILT: GSTR=0,??=0,??=0,??=0,??=0,FILT_CNT=0,FILT_PER=0 */
  setReg16(PWM_FFILT, 0x00U);           
  /* PWM_MASK: ??=0,??=0,??=0,??=0,MASKA&=~7,MASKB&=~7,MASKX&=~7 */
  clrReg16Bits(PWM_MASK, 0xF777U);      
  /* PWM_SWCOUT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,SM2OUT23=0,SM2OUT45=0,SM1OUT23=0,SM1OUT45=0,SM0OUT23=0,SM0OUT45=0 */
  clrReg16Bits(PWM_SWCOUT, 0xFF3FU);    
  /* PWM_DTSRCSEL: SM2SEL23=0,SM2SEL45=0,SM1SEL23=0,SM1SEL45=0,SM0SEL23=0,SM0SEL45=0 */
  clrReg16Bits(PWM_DTSRCSEL, 0x0FFFU);  
  /* PWM_MCTRL2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,MONPLL=0 */
  setReg16(PWM_MCTRL2, 0x00U);          
  /* PWM_OUTEN: ??=0,??=0,??=0,??=0,PWMA_EN&=~7,PWMB_EN&=~7,PWMX_EN&=~7 */
  clrReg16Bits(PWM_OUTEN, 0xF777U);     
  /* PWM_MCTRL: IPOL&=~7,RUN=0,CLDOK=0,LDOK=7 */
  clrSetReg16Bits(PWM_MCTRL, 0x7FF8U, 0x07U); 
  /* PWM_FSTS: ??=0,??=0,??=0,FTEST=0,FFPIN=0x0F,FFULL=0,FFLAG=0 */
  setReg16(PWM_FSTS, 0x0F00U);          
  /* PWM_FCTRL: FLVL=0,FAUTO=0x0F,FSAFE=0,FIE=0 */
  setReg16(PWM_FCTRL, 0x0F00U);         
  /* PWM_MCTRL: RUN|=7 */
  setReg16Bits(PWM_MCTRL, 0x0700U);     
  /* PWM_SM0_STS: ??=1,RUF=1,REF=1,RF=1,CFA1=1,CFA0=1,CFB1=1,CFB0=1,CFX1=1,CFX0=1,CMPF=0x3F */
  setReg16(PWM_SM0_STS, 0xFFFFU);       
  /* PWM_SM1_STS: ??=1,RUF=1,REF=1,RF=1,CFA1=1,CFA0=1,CFB1=1,CFB0=1,CFX1=1,CFX0=1,CMPF=0x3F */
  setReg16(PWM_SM1_STS, 0xFFFFU);       
  /* PWM_SM2_STS: ??=1,RUF=1,REF=1,RF=1,CFA1=1,CFA0=1,CFB1=1,CFB0=1,CFX1=1,CFX0=1,CMPF=0x3F */
  setReg16(PWM_SM2_STS, 0xFFFFU);       
  /* PWM_SM3_STS: ??=1,RUF=1,REF=1,RF=1,CFA1=1,CFA0=1,CFB1=1,CFB0=1,CFX1=1,CFX0=1,CMPF=0x3F */
  setReg16(PWM_SM3_STS, 0xFFFFU);       
  /* PWM_SM0_INTEN: ??=0,??=0,REIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0 */
  clrReg16Bits(PWM_SM0_INTEN, 0xEFC0U); 
  /* PWM_SM1_INTEN: ??=0,??=0,REIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0 */
  clrReg16Bits(PWM_SM1_INTEN, 0xEFC0U); 
  /* PWM_SM2_INTEN: ??=0,??=0,REIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0 */
  clrReg16Bits(PWM_SM2_INTEN, 0xEFC0U); 
  /* PWM_SM3_INTEN: ??=0,??=0,REIE=0 */
  clrReg16Bits(PWM_SM3_INTEN, 0xE000U); 
}


/* END eFPWM1. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 5.3 [05.01]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
