/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : I2C2.c
**     Project     : ProcessorExpert
**     Processor   : MC56F8257
**     Component   : InternalI2C
**     Version     : Component 01.277, Driver 02.03, CPU db: 3.00.240
**     Compiler    : Metrowerks DSP C Compiler
**     Date/Time   : 2012-12-10, 20:49, # CodeGen: 34
**     Abstract    :
**          This component encapsulates the internal I2C communication 
**          interface. The implementation of the interface is based 
**          on the Philips I2C-bus specification version 2.0. 
**          Interface features:
**          MASTER mode
**            - Multi master communication
**            - The combined format of communication possible 
**              (see "Automatic stop condition" property)
**            - 7-bit slave addressing (10-bit addressing can be made as well)
**            - Acknowledge polling provided
**            - No wait state initiated when a slave device holds the SCL line low
**            - Holding of the SCL line low by slave device recognized as 'not available bus'
**            - Invalid start/stop condition detection provided
**          SLAVE mode
**            - 7-bit slave addressing
**            - General call address detection provided
**     Settings    :
**         Serial channel              : I2C1
**
**         Protocol
**             Mode                    : MASTER
**             Auto stop condition     : yes
**             SCL frequency           : 750 kHz
**
**         Initialization
**
**             Target slave address    : 8
**             Component init          : Enabled
**             Events                  : Enabled
**
**         Registers
**             Input buffer            : I2C1_DATA [F224]
**             Output buffer           : I2C1_DATA [F224]
**             Control register        : I2C1_CR1  [F222]
**             Status register         : I2C1_SR   [F223]
**             Baud setting reg.       : I2C1_FREQDIV [F221]
**             Address register        : I2C1_ADDR [F220]
**             Glitch filter register  : I2C1_FILT [F226]
**
**
**         Used pins                   :
**       ----------------------------------------------------------
**            Function    | On package |    Name
**       ----------------------------------------------------------
**              SDA       |     40     |  GPIOF3_SDA1_XB_OUT3
**              SCL       |     39     |  GPIOF2_SCL1_XB_OUT2
**       ----------------------------------------------------------
**     Contents    :
**         SendChar    - byte I2C2_SendChar(byte Chr);
**         RecvChar    - byte I2C2_RecvChar(byte *Chr);
**         SendBlock   - byte I2C2_SendBlock(void* Ptr, word Siz, word *Snt);
**         RecvBlock   - byte I2C2_RecvBlock(void* Ptr, word Siz, word *Rcv);
**         SelectSlave - byte I2C2_SelectSlave(byte Slv);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE I2C2. */


#include "I2C2.h"

#define OVERRUN_ERR      0x01          /* Overrun error flag bit   */
#define WAIT_RX_CHAR     0x02          /* Wait for received char. flag bit (Master)  */
#define CHAR_IN_TX       0x04          /* Char is in TX buffer (Master)    */
#define CHAR_IN_RX       0x08          /* Char is in RX buffer     */
#define FULL_TX          0x10          /* Full transmit buffer     */
#define IN_PROGRES       0x20          /* Communication is in progress (Master) */
#define FULL_RX          0x40          /* Full receive buffer      */
#define MSxSL            0x80          /* Master x Slave flag bit  */

static byte I2C2_SlaveAddr;            /* Variable for Slave address */
static word InpLenM;                   /* Length of input bufer's content */
static byte *InpPtrM;                  /* Pointer to input buffer for Master mode */
static word OutLenM;                   /* Length of output bufer's content */
static byte *OutPtrM;                  /* Pointer to output buffer for Master mode */
volatile word I2C2_SndRcvTemp;         /* Temporary variable for SendChar (RecvChar) when they call SendBlock (RecvBlock) */
static word *PtrSndRcv;                /* Pointer to Snd/Rcv counter for SendBlock/RecvBlock */
static byte ChrTemp;                   /* Temporary variable for SendChar method */
volatile byte I2C2_SerFlag;            /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Wait for received char. flag bit (Master) */
                                       /*       2 - Char is in TX buffer (Master) */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - Master x Slave */

/*
** ===================================================================
**     Method      :  MainComm (component InternalI2C)
**
**     Description :
**         The method services the interrupt flags if Interrupt service 
**         is disabled.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define RXAK 0x01
#define SRW  0x04
#define IBAL 0x10
#define IAAS 0x40
static byte MainComm(void)
{
  register word Tr;
  register word Status;                /* Temporary variable for saving status register */

  *PtrSndRcv = 0;                      /* Clear Snd/Rcv counter */
  for (Tr=0; Tr<0x07D0;Tr++) {
    if (getRegBit(I2C1_SR,IICIF)) {
      Status = getReg(I2C1_SR);        /* Save status register */
      setRegBit(I2C1_SR,IICIF);        /* Clear interrupt flag */
      Tr = (word)-1;                   /* Clear trials */
      if (getRegBit(I2C1_CR1,MST)) {   /* Is device in master mode? */
        if (getRegBit(I2C1_CR1,TX)) {  /* Is device in Tx mode? */
          if (Status & I2C1_SR_RXAK_MASK) { /* NACK received? */
            clrRegBit(I2C1_CR1,MST);   /* Switch device to slave mode (stop signal sent) */
            clrRegBit(I2C1_CR1,TX);    /* Switch to Rx mode */
            OutLenM = 0;               /* Any character is not for sent */
            InpLenM = 0;               /* Any character is not for reception */
            I2C2_SerFlag &= ~(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES); /* Any character is not for sent or reception*/
            return ERR_BUSY;           /* Return with error */
          }
          else {
            if (OutLenM) {             /* Is any char. for transmitting? */
              OutLenM--;               /* Decrease number of chars for the transmit */
              setReg(I2C1_DATA,*(OutPtrM)++); /* Send character */
              (*PtrSndRcv)++;          /* Increment Snd counter */
            }
            else {
              if (InpLenM) {           /* Is any char. for reception? */
                if (InpLenM == 1)      /* If only one char to receive */
                  setRegBit(I2C1_CR1,TXAK); /* then transmit ACK disable */
                else
                  clrRegBit(I2C1_CR1,TXAK); /* else transmit ACK enable */
                clrRegBit(I2C1_CR1,TX); /* Switch to Rx mode */
                getReg(I2C1_DATA);     /* Dummy read character */
              }
              else {
                clrRegBit(I2C1_CR1,MST); /* Switch device to slave mode (stop signal sent) */
                clrRegBit(I2C1_CR1,TX); /* Switch to Rx mode */
                for (Tr=0x07D0;Tr!=0;Tr--) {
                  if (!getRegBit(I2C1_SR,BUSY)) { /* Bus is busy? */
                    return ERR_OK;     /* Return without error */
                  }
                }
                return ERR_BUSOFF;     /* Return with error */
              }
            }
          }
        }
        else {
          InpLenM--;                   /* Decrease number of chars for the receive */
          if (InpLenM) {               /* Is any char. for reception? */
            if (InpLenM == 1)
              setRegBit(I2C1_CR1,TXAK); /* Transmit ACK disable */
          }
          else {
            clrRegBit(I2C1_CR1,MST);   /* If no, switch device to slave mode (stop signal sent) */
          }
          *(InpPtrM)++ = (byte)getReg(I2C1_DATA); /* Receive character */
          (*PtrSndRcv)++;              /* Increment Rcv counter */
          if (!InpLenM) {              /* Is any char. for reception? */
            for (Tr=0x07D0;Tr!=0;Tr--) {
              if (!getRegBit(I2C1_SR,BUSY)) { /* Bus is busy? */
                return ERR_OK;         /* Return without error */
              }
            }
            return ERR_BUSOFF;         /* Return with error */
          }
        }
      }
      else {
        if (Status & I2C1_SR_ARBL_MASK) { /* Arbitration lost? */
          OutLenM = 0;                 /* Any character is not for sent */
          InpLenM = 0;                 /* Any character is not for reception */
          I2C2_SerFlag &= ~(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES); /* Any character is not for sent or reception*/
          clrRegBit(I2C1_CR1,TX);      /* Switch to Rx mode */
          return ERR_ARBITR;           /* Return with error */
        }
      }
    }
  }
  return ERR_BUSOFF;                   /* Return with error */
}

/*
** ===================================================================
**     Method      :  I2C2_SendChar (component InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address bytes
**         inclusive of R/W bit = 0 to the I2C bus and then writes one
**         character (byte) to the bus. The slave address must be
**         specified before, by the "SelectSlave" or "SelectSlave10"
**         method or in the component initialization section, "Target
**         slave address init" property. If interrupt service is
**         enabled and the method returns ERR_OK, it doesn't mean that
**         transmission was successful. The state of transmission is
**         obtainable from (OnTransmitData, OnError or OnArbitLost)
**         events. 
**         When working as a SLAVE, this method writes a character to
**         the internal output slave buffer and, after the master
**         starts the communication, to the I2C bus. If no character is
**         ready for a transmission (internal output slave buffer is
**         empty), the Empty character will be sent (see "Empty
**         character" property).
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by an acknowledge (only in
**                           master mode and when interrupt service is
**                           disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot transmit data
**                           ERR_TXFULL - Transmitter is full (slave
**                           mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in master
**                           mode)
** ===================================================================
*/
byte I2C2_SendChar(byte Chr)
{
  if ((getRegBit(I2C1_SR,BUSY))||(InpLenM)||(I2C2_SerFlag&(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES))) { /* Is the bus busy */
    return ERR_BUSOFF;                 /* If yes then error */
  }
  ChrTemp = Chr;                       /* Save character */
  return (I2C2_SendBlock(&ChrTemp, 1, (word*)&I2C2_SndRcvTemp)); /* Send character and return */
}

/*
** ===================================================================
**     Method      :  I2C2_RecvChar (component InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address bytes
**         inclusive of R/W bit = 1 to the I2C bus, then reads one
**         character (byte) from the bus and then sends the stop
**         condition. The slave address must be specified before, by
**         the "SelectSlave" or "SelectSlave10" method or in component
**         initialization section, property "Target slave address init".
**         If interrupt service is enabled and the method returns
**         ERR_OK, it doesn't mean that transmission was finished
**         successfully. The state of transmission must be tested by
**         means of events (OnReceiveData, OnError or OnArbitLost). In
**         case of successful transmission, received data is ready
**         after OnReceiveData event is called. 
**         When working as a SLAVE, this method reads a character from
**         the input slave buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Received character.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledge (only
**                           in master mode and when interrupt service
**                           is disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot receive data
**                           ERR_RXEMPTY - No data in receiver (slave
**                           mode only)
**                           ERR_OVERRUN - Overrun error was detected
**                           from the last character or block received
**                           (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in master
**                           mode)
**                           ERR_NOTAVAIL - Method is not available in
**                           current mode - see the comment in the
**                           generated code
** ===================================================================
*/
/*
byte I2C2_RecvChar(byte *Chr)

**  This method is implemented as a macro. See I2C2.h file.  **
*/

/*
** ===================================================================
**     Method      :  I2C2_SendBlock (component InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address bytes
**         inclusive of R/W bit = 0 to the I2C bus and then writes the
**         block of characters to the bus. The slave address must be
**         specified before, by the "SelectSlave" or "SlaveSelect10"
**         method or in component initialization section, "Target slave
**         address init" property. If interrupt service is enabled and
**         the method returns ERR_OK, it doesn't mean that transmission
**         was successful. The state of transmission is detectable by
**         means of events (OnTransmitData, OnError or OnArbitLost).
**         Data to be send is not copied to an internal buffer and
**         remains in the original location. Therefore the content of
**         the buffer should not be changed until the transmission is
**         complete. Event OnTransmitData can be used to detect the end
**         of the transmission.
**         When working as a SLAVE, this method writes a block of
**         characters to the internal output slave buffer and then,
**         after the master starts the communication, to the I2C bus.
**         If no character is ready for a transmission (internal output
**         slave buffer is empty), the "Empty character" will be sent
**         (see "Empty character" property). In SLAVE mode the data are
**         copied to an internal buffer, if specified by "Output buffer
**         size" property.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of data to send.
**         Siz             - Size of the block.
**       * Snt             - Amount of data sent (moved to a buffer).
**                           In master mode, if interrupt support is
**                           enabled, the parameter always returns the
**                           same value as the parameter 'Siz' of this
**                           method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledge (only
**                           in master mode and when interrupt service
**                           is disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot transmit data
**                           ERR_TXFULL - Transmitter is full. Some data
**                           has not been sent. (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in master
**                           mode)
** ===================================================================
*/
byte I2C2_SendBlock(void* Ptr,word Siz,word *Snt)
{
  if (!Siz) {                          /* Test variable Size on zero */
    *Snt = 0;
    return ERR_OK;                     /* If zero then OK */
  }
  if ((getRegBit(I2C1_SR,BUSY))||(InpLenM)||(I2C2_SerFlag&(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES))) { /* Is the bus busy */
    return ERR_BUSOFF;                 /* If yes then error */
  }
  PtrSndRcv = Snt;                     /* Safe Snd pointer */
  OutLenM = Siz;                       /* Set lenght of data */
  OutPtrM = (byte *)Ptr;               /* Save pointer to data for transmitting */
  setRegBit(I2C1_CR1,TX);              /* Set TX mode */
  if (getRegBit(I2C1_CR1,MST)) {       /* Is device in master mode? */
    setRegBit(I2C1_CR1,RSTA);          /* If yes then repeat start cycle generated */
  }
  else {
    setRegBit(I2C1_CR1,MST);           /* If no then start signal generated */
  }
  setReg(I2C1_DATA,I2C2_SlaveAddr);    /* Send slave address */
  return (MainComm());                 /* Call main communication method and return */
}

/*
** ===================================================================
**     Method      :  I2C2_RecvBlock (component InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address bytes
**         inclusive of R/W bit = 1 to the I2C bus, then reads the
**         block of characters from the bus and then sends the stop
**         condition. The slave address must be specified before, by
**         the "SelectSlave" or "SelectSlave10" method or in component
**         initialization section, "Target slave address init" property.
**         If interrupt service is enabled and the method returns
**         ERR_OK, it doesn't mean that transmission was finished
**         successfully. The state of transmission must be tested by
**         means of events (OnReceiveData, OnError or OnArbitLost). In
**         case of successful transmission, received data is ready
**         after OnReceiveData event is called. 
**         When working as a SLAVE, this method reads a block of
**         characters from the input slave buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - A pointer to the block space for received
**                           data.
**         Siz             - The size of the block.
**       * Rcv             - Amount of received data. In master mode,
**                           if interrupt support is enabled, the
**                           parameter always returns the same value as
**                           the parameter 'Siz' of this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by an acknowledge (only in
**                           master mode and when interrupt service is
**                           disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot receive data
**                           ERR_RXEMPTY - The receive buffer didn't
**                           contain the requested number of data. Only
**                           available data (or no data) has been
**                           returned  (slave mode only).
**                           ERR_OVERRUN - Overrun error was detected
**                           from last character or block receiving
**                           (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in master
**                           mode)
**                           ERR_NOTAVAIL - Method is not available in
**                           current mode - see the comment in the
**                           generated code.
** ===================================================================
*/
byte I2C2_RecvBlock(void* Ptr,word Siz,word *Rcv)
{
  if (!Siz) {                          /* Test variable Size on zero */
    *Rcv = 0;
    return ERR_OK;                     /* If zero then OK */
  }
  if ((getRegBit(I2C1_SR,BUSY))||(InpLenM)||(I2C2_SerFlag&(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES))) { /* Is the bus busy */
    return ERR_BUSOFF;                 /* If yes then error */
  }
  PtrSndRcv = Rcv;                     /* Safe Rcv pointer */
  InpLenM = Siz;                       /* Set lenght of data */
  InpPtrM = (byte *)Ptr;               /* Save pointer to data for reception */
  setRegBit(I2C1_CR1,TX);              /* Set TX mode */
  if (getRegBit(I2C1_CR1,MST)) {       /* Is device in master mode? */
    setRegBit(I2C1_CR1,RSTA);          /* If yes then repeat start cycle generated */
  }
  else {
    setRegBit(I2C1_CR1,MST);           /* If no then start signal generated */
  }
  setReg(I2C1_DATA,(byte)(I2C2_SlaveAddr+1)); /* Send slave address */
  return (MainComm());                 /* Call main communication method and return */
}

/*
** ===================================================================
**     Method      :  I2C2_SelectSlave (component InternalI2C)
**
**     Description :
**         This method selects a new slave for communication by its
**         7-bit slave address value. Any send or receive method
**         directs to or from selected device, until a new slave device
**         is selected by this method. This method is not available for
**         the SLAVE mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Slv             - 7-bit slave address value.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_BUSY - The device is busy, wait until
**                           the current operation is finished.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  The device is disabled
** ===================================================================
*/
byte I2C2_SelectSlave(byte Slv)
{
  if (getRegBit(I2C1_CR1,MST)) {       /* Is the device in the active state? */
    return ERR_BUSY;                   /* If yes then error */
  }
  I2C2_SlaveAddr = (byte)(Slv << 1);   /* Set slave address */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C2_Init (component InternalI2C)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void I2C2_Init(void)
{
  /* I2C1_CR1: IICEN=0,IICIE=0,MST=0,TX=0,TXAK=0,RSTA=0,WUEN=0,??=0 */
  setReg(I2C1_CR1,0);                  /* Clear control register */
  I2C2_SerFlag = 0x80;                 /* Reset all flags */
  I2C2_SlaveAddr = 0x10;               /* Set variable for slave address */
  /* I2C1_FILT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FLT2=0,FLT1=0,FLT0=0 */
  setReg(I2C1_FILT,0x00);              /* Set glitch filter register */
  /* I2C1_FREQDIV: MULT=2,TAP2=0,TAP1=0 */
  setReg(I2C1_FREQDIV,0x80);           /* Set prescaler bits */
  /* I2C1_SMB_CSR: FACK=0,ALERTEN=0,SIICAEN=0,TCKSEL=0,SLTF=1,SHTF=0,SHTF2=0,SHTF2IE=0 */
  setReg(I2C1_SMB_CSR,0x08);
  setRegBit(I2C1_CR1,IICEN);           /* Enable device */
}


/* END I2C2. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 5.3 [05.01]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
